### ISSUE TITLE
Uptime math a bit odd

### ISSUE THREAD

**Issue by filiptronicek** [koj-co/status#13]
The uptime % in the README can go under 0%, probably an error from here:
https://github.com/koj-co/status/blob/3060f3aeffb9002c733ec61e5b58b4c5da8b3143/summary.ts#L73-L77

That gets displayed here:
https://github.com/koj-co/status/blob/3060f3aeffb9002c733ec61e5b58b4c5da8b3143/summary.ts#L118

Which leads to this:
![uptime in table showing -4050.85%](https://user-images.githubusercontent.com/29888641/89730119-3c225f80-da3c-11ea-8440-31091d0a04e3.png)

**Comment by AnandChowdhary** [comment]
Yep, this is something I'm working on! 😄

**Comment by AnandChowdhary** [comment]
This is fixed!

<img width="748" alt="Screen Shot 2020-08-09 at 16 23 23@2x" src="https://user-images.githubusercontent.com/2841780/89730495-aea33780-da5c-11ea-978b-9e1685f4c701.png">
